name: Security Checks
on: [push]

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
        
    steps:
       - uses: actions/checkout@v2
         with:
            persist-credentials: false 
            ref: master
       - name: Building Docker Node-Goat Image
         run: docker-compose build
       - name: Launching the app
         run: docker-compose up --detach



       - name: OWASP ZAP
         uses: zaproxy/action-full-scan@v0.4.0
         with:
            # GitHub Token to create issues in the repository
            token: $
    # Target URL
            target: "http://localhost:4000"

            fail_action: false
    # Whether Github issues should be created or not
            

         
